# NordVPN egress for the acquisition half of the arr stack, via a network
# namespace.
#
# Why a namespace rather than a policy route or a per-process cgroup: a
# namespace has its own routing table, and the only default route we put in it
# is the WireGuard interface.
# That makes the kill switch structural rather than a rule that has to fire.
# If wg0 goes away the default route goes with it - the namespace is not
# "leaking to the LAN", it simply has nowhere to send a packet.
# Nothing has to notice the tunnel dropped for the protection to hold.
#
# What is in it: Sonarr, Radarr, Prowlarr, SABnzbd.
# Prowlarr is not enough on its own - it syncs indexer definitions *into*
# Sonarr and Radarr over their APIs, and from then on those two query the
# indexers themselves.
# Masking Prowlarr while Sonarr talks to the same indexer from the home IP
# would be theatre.
#
# What is not: Jellyfin, Bazarr, Jellyseerr.
# Jellyfin serves the tailnet and should be reachable at full LAN speed,
# Bazarr fetches subtitles, Jellyseerr is a request UI.
# None of them touch an indexer.
#
# 📎 On Usenet specifically: the download itself is TLS to a paid provider and
# no peers ever see the IP, so this hides *that Usenet is in use* from the ISP
# rather than closing an exposure to strangers.
# That calculus changes completely the day a torrent client is added, which is
# the case this is really built for.
{ config, lib, pkgs, morty-alert, ... }:
let
  ns = "vpn";
  nsPath = "/var/run/netns/${ns}";

  # /30: two usable addresses, which is exactly the population.
  hostAddr = "10.200.0.1";
  nsAddr = "10.200.0.2";
  vethHost = "veth-vpn";
  vethNs = "veth-vpn-ns";

  # The same link in v6. MagicDNS publishes both an A and a AAAA for morty and
  # a browser will try the AAAA first, so an IPv4-only forward means the UIs
  # look dead from the laptop while working perfectly over the v4 literal.
  # Found exactly that way.
  #
  # Note there is deliberately no v6 default route inside the namespace: the
  # NordVPN config assigns an IPv4 tunnel address only, so v6 has nowhere to
  # go and cannot leak. This ULA reaches morty across the veth and nothing
  # else.
  hostAddr6 = "fd00:200::1";
  nsAddr6 = "fd00:200::2";

  # Generated by wgnord from the NordVPN access token in the 1Password Morty
  # vault, kept out of the flake because it carries a private key.
  wgConf = "/var/lib/morty-backup/nordvpn/wg0.conf";

  # NordVPN's own resolvers, reachable only through the tunnel.
  # Using them rather than the LAN's means DNS for anything inside the
  # namespace does not go to the ISP either - a DNS leak tells the same story a
  # traffic leak does.
  nsDns = [ "103.86.96.100" "103.86.99.100" ];

  # Web UIs that must stay reachable from the tailnet even though the service
  # itself lives in the namespace.
  forwardedPorts = [ 8989 7878 9696 8080 ];

  nsServices = [ "sonarr" "radarr" "prowlarr" "sabnzbd" ];

  iptables = "${pkgs.iptables}/bin/iptables";
  ip6tables = "${pkgs.iptables}/bin/ip6tables";
in
{
  # `ip netns exec` bind-mounts this over /etc/resolv.conf.
  # systemd's NetworkNamespacePath does *not* do the same, so the services
  # below get the file through BindReadOnlyPaths instead - easy to miss, and
  # the symptom is a service that resolves nothing while the namespace works
  # perfectly by hand.
  environment.etc."netns/${ns}/resolv.conf".text =
    lib.concatMapStrings (s: "nameserver ${s}\n") nsDns;

  systemd.services = {
    "netns-${ns}" = {
      description = "Network namespace ${ns} with NordVPN as its only route out";
      wantedBy = [ "multi-user.target" ];
      after = [ "network-online.target" ];
      wants = [ "network-online.target" ];

      # The conf carries the private key. If it is missing, fail loudly rather
      # than build a namespace with no tunnel in it.
      unitConfig.ConditionPathExists = wgConf;

      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
      };

      path = [ pkgs.iproute2 pkgs.wireguard-tools pkgs.gnugrep pkgs.coreutils ];

      script = ''
        set -euo pipefail

        # A run that died partway leaves the namespace behind, and `netns add`
        # on an existing name is a hard error.
        ip netns del ${ns} 2>/dev/null || true
        ip link del ${vethHost} 2>/dev/null || true

        ip netns add ${ns}
        ip netns exec ${ns} ip link set lo up

        # The veth pair is the only way in or out besides the tunnel, and it
        # carries no default route - just the /30. That is the kill switch.
        ip link add ${vethHost} type veth peer name ${vethNs}
        ip link set ${vethNs} netns ${ns}
        ip addr add ${hostAddr}/30 dev ${vethHost}
        ip link set ${vethHost} up
        ip netns exec ${ns} ip addr add ${nsAddr}/30 dev ${vethNs}
        ip addr add ${hostAddr6}/126 dev ${vethHost}
        ip netns exec ${ns} ip addr add ${nsAddr6}/126 dev ${vethNs}
        ip netns exec ${ns} ip link set ${vethNs} up

        # Create wg0 in the *host* namespace and then move it.
        # A WireGuard interface remembers where it was born and keeps its
        # encrypted UDP socket there, so the outer packets to NordVPN are sent
        # from the host's routing table.
        # That is precisely what lets the namespace itself have no route to the
        # internet at all. Build it inside instead and you get a
        # chicken-and-egg: the tunnel needs egress the namespace does not have.
        ip link add wg0 type wireguard
        ip link set wg0 netns ${ns}

        # wg setconf takes only the protocol fields. Address, DNS and MTU are
        # wg-quick's own extensions and it rejects them.
        umask 077
        conf=$(mktemp)
        trap 'rm -f "$conf"' EXIT
        grep -vE '^[[:space:]]*(Address|DNS|MTU)[[:space:]]*=' ${wgConf} > "$conf"
        ip netns exec ${ns} wg setconf wg0 "$conf"

        ip netns exec ${ns} ip addr add 10.5.0.2/32 dev wg0
        ip netns exec ${ns} ip link set wg0 mtu 1350 up
        ip netns exec ${ns} ip route add default dev wg0
      '';

      preStop = ''
        ip netns del ${ns} 2>/dev/null || true
        ip link del ${vethHost} 2>/dev/null || true
      '';
    };

    # The verification.
    # The kill switch above is structural, so this is not what stops a leak -
    # it is what proves the thing is doing the job it claims to be doing, a
    # distinction this setup has earned the hard way.
    # wgnord's first config this week pointed at a Brazilian endpoint while
    # reporting success; "I asked for the UK" is not evidence.
    vpn-check = {
      description = "Check that the ${ns} namespace egresses somewhere other than home";
      after = [ "netns-${ns}.service" ];
      requires = [ "netns-${ns}.service" ];
      restartIfChanged = false;
      serviceConfig.Type = "oneshot";
      path = [ pkgs.iproute2 pkgs.curl pkgs.jq pkgs.systemd morty-alert ];
      script = ''
        set -uo pipefail

        home=$(curl -fsS --max-time 20 https://ipinfo.io/ip || true)
        vpn=$(ip netns exec ${ns} curl -fsS --max-time 20 https://ipinfo.io/ip || true)

        if [ -z "$vpn" ]; then
          printf 'The %s namespace could not reach the internet (home=%s).\n\nThe tunnel is down, so Sonarr, Radarr, Prowlarr and SABnzbd have no egress at all. That is the intended failure mode rather than a leak, but nothing will download until it is back.\n' \
            ${ns} "''${home:-unknown}" | morty-alert "VPN tunnel down"
          exit 1
        fi

        if [ -n "$home" ] && [ "$vpn" = "$home" ]; then
          printf 'The %s namespace egressed from %s, which is the home IP.\n\nTraffic that should be tunnelled is not. Stopping the four services.\n' \
            ${ns} "$vpn" | morty-alert "VPN LEAK"
          systemctl stop ${lib.concatStringsSep " " nsServices}
          exit 1
        fi

        geo=$(ip netns exec ${ns} curl -fsS --max-time 20 "https://ipinfo.io/$vpn" \
          | jq -r '"\(.city), \(.country) (\(.org))"' || echo unknown)
        echo "${ns} egress $vpn - $geo (home ''${home:-unknown})"
      '';
    };
  }
  # Move the four services in.
  # BindsTo rather than Requires: if the namespace unit stops, these stop with
  # it rather than carrying on in the host network.
  // lib.genAttrs nsServices (_: {
    after = [ "netns-${ns}.service" ];
    bindsTo = [ "netns-${ns}.service" ];
    serviceConfig = {
      NetworkNamespacePath = nsPath;
      BindReadOnlyPaths = [ "/etc/netns/${ns}/resolv.conf:/etc/resolv.conf" ];
    };
  });

  systemd.timers.vpn-check = {
    wantedBy = [ "timers.target" ];
    timerConfig = {
      OnBootSec = "5m";
      OnUnitActiveSec = "1h";
      RandomizedDelaySec = "5m";
    };
  };

  # Forwarding between the tailnet and the namespace, plus the DNAT that keeps
  # the web UIs on their usual ports.
  #
  # These live in the firewall rather than in netns-vpn so that a firewall
  # reload - which flushes the tables - puts them back.
  # They name an interface that need not exist yet, which iptables accepts.
  networking.firewall.extraCommands = ''
    ${iptables} -t nat -N MORTY_VPN_DNAT 2>/dev/null || ${iptables} -t nat -F MORTY_VPN_DNAT
    ${lib.concatMapStrings (p: ''
      ${iptables} -t nat -A MORTY_VPN_DNAT -p tcp --dport ${toString p} -j DNAT --to-destination ${nsAddr}:${toString p}
    '') forwardedPorts}
    # From the tailnet.
    ${iptables} -t nat -A PREROUTING -i tailscale0 -j MORTY_VPN_DNAT
    # From morty itself, for Bazarr and Jellyseerr - they stayed on the host
    # network and reach Sonarr and Radarr over morty's own address.
    #
    # Deliberately every local address *except* 127.0.0.0/8. DNAT of a
    # loopback destination leaves the source as 127.0.0.1 while rerouting the
    # packet out veth-vpn, and the kernel drops that as a martian before
    # MASQUERADE can fix the source. Working around it means
    # net.ipv4.conf.all.route_localnet=1, which makes 127/8 addressable from
    # the wire - far too big a hole for the convenience of typing localhost.
    # So configure those two against `morty:8989`, not `localhost:8989`.
    ${iptables} -t nat -A OUTPUT -m addrtype --dst-type LOCAL ! -d 127.0.0.0/8 -j MORTY_VPN_DNAT

    # Replies must come back through the host, not out of the tunnel.
    # Without this the namespace answers a 100.x tailnet address via its
    # default route, which is wg0, and the connection simply hangs.
    ${iptables} -t nat -A POSTROUTING -o ${vethHost} -j MASQUERADE

    ${iptables} -A FORWARD -o ${vethHost} -j ACCEPT
    ${iptables} -A FORWARD -i ${vethHost} -j ACCEPT

    # The one thing the namespace needs *from* the host: Sonarr and Radarr
    # telling Jellyfin to rescan after an import. Jellyfin stayed on the host
    # network, so without this the library only updates on its timer and a
    # finished episode sits invisible for hours.
    #
    # Deliberately one port from one address rather than trusting the
    # interface. The namespace is not a trusted zone - it is the zone whose
    # egress we do not control.
    ${iptables} -A INPUT -i ${vethHost} -s ${nsAddr} -p tcp --dport 8096 -j ACCEPT

    # The v6 mirror of all of the above.
    ${ip6tables} -t nat -N MORTY_VPN_DNAT 2>/dev/null || ${ip6tables} -t nat -F MORTY_VPN_DNAT
    ${lib.concatMapStrings (p: ''
      ${ip6tables} -t nat -A MORTY_VPN_DNAT -p tcp --dport ${toString p} -j DNAT --to-destination [${nsAddr6}]:${toString p}
    '') forwardedPorts}
    ${ip6tables} -t nat -A PREROUTING -i tailscale0 -j MORTY_VPN_DNAT
    ${ip6tables} -t nat -A OUTPUT -m addrtype --dst-type LOCAL ! -d ::1/128 -j MORTY_VPN_DNAT
    ${ip6tables} -t nat -A POSTROUTING -o ${vethHost} -j MASQUERADE
    ${ip6tables} -A FORWARD -o ${vethHost} -j ACCEPT
    ${ip6tables} -A FORWARD -i ${vethHost} -j ACCEPT
  '';

  boot.kernel.sysctl."net.ipv4.ip_forward" = true;
  boot.kernel.sysctl."net.ipv6.conf.all.forwarding" = true;

  networking.firewall.extraStopCommands = ''
    ${iptables} -t nat -D PREROUTING -i tailscale0 -j MORTY_VPN_DNAT 2>/dev/null || true
    ${iptables} -t nat -D OUTPUT -m addrtype --dst-type LOCAL ! -d 127.0.0.0/8 -j MORTY_VPN_DNAT 2>/dev/null || true
    ${iptables} -t nat -D POSTROUTING -o ${vethHost} -j MASQUERADE 2>/dev/null || true
    ${iptables} -D FORWARD -o ${vethHost} -j ACCEPT 2>/dev/null || true
    ${iptables} -D FORWARD -i ${vethHost} -j ACCEPT 2>/dev/null || true
    ${iptables} -D INPUT -i ${vethHost} -s ${nsAddr} -p tcp --dport 8096 -j ACCEPT 2>/dev/null || true
    ${iptables} -t nat -F MORTY_VPN_DNAT 2>/dev/null || true
    ${iptables} -t nat -X MORTY_VPN_DNAT 2>/dev/null || true

    ${ip6tables} -t nat -D PREROUTING -i tailscale0 -j MORTY_VPN_DNAT 2>/dev/null || true
    ${ip6tables} -t nat -D OUTPUT -m addrtype --dst-type LOCAL ! -d ::1/128 -j MORTY_VPN_DNAT 2>/dev/null || true
    ${ip6tables} -t nat -D POSTROUTING -o ${vethHost} -j MASQUERADE 2>/dev/null || true
    ${ip6tables} -D FORWARD -o ${vethHost} -j ACCEPT 2>/dev/null || true
    ${ip6tables} -D FORWARD -i ${vethHost} -j ACCEPT 2>/dev/null || true
    ${ip6tables} -t nat -F MORTY_VPN_DNAT 2>/dev/null || true
    ${ip6tables} -t nat -X MORTY_VPN_DNAT 2>/dev/null || true
  '';
}
